language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

notifications:
  email:
    - jnesselr@harding.edu

# whitelist
branches:
  only:
    - master
    - cakephp

before_install:
  - sudo apt-get update > /dev/null

install:
  # Install the packages we need
  - sudo apt-get install -y --force-yes php5-mysql php-pear build-essential php5-curl php5-dev libmagic-dev

  # Install composer
  - composer self-update
  - composer install
  
before_script:
  - cp extensions/config-travis.php extensions/config.php

script:
  - phpunit --bootstrap extensions/global.php tests
